# ===========================================
# CLOUD SENTINEL - Checkov Configuration
# ===========================================

# Frameworks to scan
framework:
  - terraform

# Output format
output:
  - cli
  - json

# Compact output
compact: true

# Directory to scan (relative to where checkov is run)
directory:
  - terraform

# Checks to skip (use sparingly!)
# For demo purposes, we want to see ALL violations
skip-check: []

# Soft fail - don't exit with error code on failures
# Set to true for demo to show violations without blocking pipeline
soft-fail: true

# Download external modules
download-external-modules: true

# Evaluate variables
evaluate-variables: true

# Enable secrets scanning
enable-secret-scan-all-files: true
# Custom policies directory (for future use)
# external-checks-dir:
#   - custom_policies/
